// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaypZqpxahTRqIpcVcw1k0IMk-fMcTRi8',
    appId: '1:999266132851:web:71c7479ec88ba5f8f81b06',
    messagingSenderId: '999266132851',
    projectId: 'food-app-c3b1c',
    authDomain: 'food-app-c3b1c.firebaseapp.com',
    storageBucket: 'food-app-c3b1c.appspot.com',
    measurementId: 'G-8P7L3RNECD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXlxxGmO9gtnpbDbNWSgg5CZ4c776Xfe4',
    appId: '1:999266132851:android:5a5670120ca737bcf81b06',
    messagingSenderId: '999266132851',
    projectId: 'food-app-c3b1c',
    storageBucket: 'food-app-c3b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4oY9WsSG1WnC9vISZV_kSmtGEUueSyU',
    appId: '1:999266132851:ios:6e6337cf517736bcf81b06',
    messagingSenderId: '999266132851',
    projectId: 'food-app-c3b1c',
    storageBucket: 'food-app-c3b1c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ4oY9WsSG1WnC9vISZV_kSmtGEUueSyU',
    appId: '1:999266132851:ios:6e6337cf517736bcf81b06',
    messagingSenderId: '999266132851',
    projectId: 'food-app-c3b1c',
    storageBucket: 'food-app-c3b1c.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
